### ISSUE TITLE
Feature request: print version on main screen

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#155]
Mini thing that helps to avoid version confusion: consider printing TR1Main's version in the bottom right corner of the main menu.

**Comment by oziphantom** [comment]
60fps has the version in the top right of the menu, so this could merge in once 60fps is approved.

**Comment by Richard-L** [comment]
How will you turn 60fps on or off? Ie if the game is set to run at 30fps, would it still print the version number?

**Comment by rr-** [comment]
Actually I removed that `RC1` label from the 60 FPS branch since it wouldn't make much sense in the context of the main branch. But it can be easily restored and the code for this label can be looked up.

In any case let's not mix up features – this ticket is only about the label for the version, and 60 fps is only for 30-60 fps switch.

**Comment by Defrago** [comment]
I think it should only be enabled to WIP builds as we already introduced DLL versions in [e5f805a](https://github.com/rr-/Tomb1Main/commit/e5f805a43442da5e8959c51a86705027d6d8b746)

**Comment by rr-** [comment]
@Richard-L ?

**Comment by thatguyfrombb** [comment]
Personal opinion, having this always forced on would help if we want to track bugs from streamers. 99% of them are bound to show the main menu, letting us know if they're up to date in the process.

**Comment by rr-** [comment]
Actually that's a very compelling reason to add it. Let's go with it.

**Comment by Richard-L** [comment]
Definitely agree with @thatguyfrombb. Think it should always be on. If we must, you could add a show/hide in JSON 🤷‍♂️
