### ISSUE TITLE
OG bugfix: fix trapdoor setting you on fire

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#2]
Current behavior:

Sometimes under rare circumstances jumping onto a drawbridge above a lava pit can cause Lara to catch on fire.

Desired behavior:

Lara doesn't catch fire.

**Comment by walkawayy** [comment]
Potentially related to #256

**Comment by walkawayy** [comment]
https://streamable.com/wvuv1v

**Comment by rr-** [comment]
Not just corners:
https://www.twitch.tv/nismoesperanza/clip/AmazonianGleamingWalrusOptimizePrime

**Comment by walkawayy** [comment]
Here's a summary of what happens:

Here's the floor indexes in question:
![image](https://user-images.githubusercontent.com/81546780/148127285-44ee3663-7ebd-4915-80ef-033fdfd72556.png)

![image](https://user-images.githubusercontent.com/81546780/148127335-255a4ea4-ff28-4965-9e2b-f1d1b20165a1.png)

Here's some values when Lara is set on fire:
```
// NO FIRE         item->floor: -18688 != height: -16640, index: 3459
// BRIDGE FIRE     item->floor: -18688 == height: -18688, index: 3434
// REAL FIRE       item->floor: -16640 == height: -16640, index: 3459
```

Correctly NOT setting Lara on fire when Lara standing on bridge:
../src/game/control.c 505 TestTriggers g_LaraItem->pos.y: -18688
../src/game/control.c 506 TestTriggers g_LaraItem->floor: -18688
../src/game/objects/trapdoor.c 47 TrapDoorFloor y: 32000
../src/game/objects/trapdoor.c 48 TrapDoorFloor item->pos.y: -18688
../src/game/objects/trapdoor.c 49 TrapDoorFloor height: -16640
../src/game/objects/trapdoor.c 60 TrapDoorFloor Don't set trap height.
../src/game/traps/lava.c 53 LavaBurn NO FIRE item->floor: -18688 != height: -16640

Incorrectly SETTING Lara on fire on the bridge/solid ground :
```
../src/game/control.c 505 TestTriggers g_LaraItem->pos.y: -18688
../src/game/control.c 506 TestTriggers g_LaraItem->floor: -18688
../src/game/traps/lava.c 60 LavaBurn SET FIRE item->floor: -18688 == height: -18688
```


When Lara is on a trapdoor above lava, the game constantly checks if Lara should be set on fire. Normally, when Lara is on a trapdoor, `TrapDoorFloor` changes `height` to that of the bridge. Thus when in `GetFloor` is called in `LavaBurn`, `item->floor != height` meaning Lara is not burned. However, in the bugged cases, Lara can move from trapdoor to solid ground and in`LavaBurn`, the `GetFloor` wrongly uses the solid ground floor index instead of the bridge when checking if Lara should be burned. So when `GetFloor` is called, her `item->floor == height` which sets her on fire.

I'm not sure how to fix it yet.

**Comment by walkawayy** [comment]
@rr- What do you think of this?

```
void LavaBurn(ITEM_INFO *item)
{
    if (g_Lara.water_status == LWS_CHEAT) {
        return;
    }

    if (item->hit_points < 0) {
        return;
    }

    int16_t room_num = item->room_number;
    FLOOR_INFO *floor = GetFloor(item->pos.x, 32000, item->pos.z, &room_num);
    int16_t height = GetHeight(floor, item->pos.x, 32000, item->pos.z);

    // OG fix: check if floor has lava
    if (floor->index) {
        int16_t *data = &g_FloorData[floor->index];
        if ((data[0] & DATA_TYPE) != FT_LAVA) {
            LOG_DEBUG("NOT on lava tile");
            return;
        }
    }

    if (item->floor != height) {
        return;
    }

    item->hit_points = -1;
    item->hit_status = 1;
    for (int i = 0; i < 10; i++) {
        int16_t fx_num = CreateEffect(item->room_number);
        if (fx_num != NO_ITEM) {
            FX_INFO *fx = &g_Effects[fx_num];
            fx->object_number = O_FLAME;
            fx->frame_number =
                (g_Objects[O_FLAME].nmeshes * Random_GetControl()) / 0x7FFF;
            fx->counter = -1 - Random_GetControl() * 24 / 0x7FFF;
        }
    }
}
```

**Comment by walkawayy** [comment]
Here's a video of the same spot lighting Lara on fire from earlier:
https://streamable.com/8jykh2

**Comment by rr-** [comment]
LGTM.

**Comment by walkawayy** [comment]
Um idk. Maybe I'll ask in the Discord.

Also found a bug with the fix. :/ Let go of the trapdoor in Great Pyramid and this happened. Lava burned Lara in other places I checked though so I'll look into it.

![image](https://user-images.githubusercontent.com/81546780/148236690-8168e1a0-7973-4ef4-b1b6-6bb7ed1d6e43.png)

**Comment by walkawayy** [comment]
> LGTM. But I'm not good at comprehending TestTriggers. Specifically `data[0]` looks suspicious. Do we have any tiles in the game that are both lava and trigger something else? For example an enemy?

I think you're right. This tile I think fails to register as lava the way I checked because it's also tilted. I have a change I'm going to try.
