### ISSUE TITLE
Feature request: allow control of TRUB music

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#216]
Since TRUB was made exclusively for PC, its levels have no music triggers for PS1/Saturn OST tracks. They were later added by fans. Thus the JSON would ideally have a "use fan-made TRUB music triggers" true/false setting.

Different triggers exist. This was the first fan rendition apparently: https://www.tombraiderforums.com/showthread.php?t=213223

Then there are two PS1 conversions, one by gh0stblade and jonathanrij, and one by b122251. I don't know about the first, but latter uses different triggers yet. I don't think TR1M needs to support them all, but it would be nice to turn them off.

A follow up issue would then be that in TRUB music triggers don't use up, they will replay the music whenever you step on them if music has finished. But we can separate that.

**Comment by rr-** [comment]
I'm against this because it's a [feature creep](https://en.wikipedia.org/wiki/Feature_creep). If you want to play other level files, just use these. The pyramid secret trigger fix is sketchy enough, I don't want to sprinkle the code with such dingbats all over the place.
@oziphantom @thatguyfrombb let me know your thoughts about this.

**Comment by Richard-L** [comment]
Well the only legitimate assets would be those from the authentic UB or Gold CDs, and those won't have music triggers, or even the soundtracks to begin with.

**Comment by thatguyfrombb** [comment]
Personally, I'd be more in favor of *adding* the triggers rather than removing them. Anyway, I wouldn't root for that either, since there are at least 2 well known options where their authors decided to use different tracks, so there's no consensus.

On just removing the triggers, if they are in the levels the users must have made a conscious choice to have them, TombATI ships bare and T1M currently doesn't even ship in a ready-to-run form. It's not needed. *Could* be nice to have once we have **everything else** sorted out.

**Comment by Richard-L** [comment]
Yeah I misunderstood because I didn't figure TombATI comes with TRUB that _already_ uses the fan triggers. Thus depending on provided assets, the user seems to already be in a position to control this.

That's how it is, right?

Thus the added layer of removing triggers manually via code would indeed seem unnecessary.

**Comment by thatguyfrombb** [comment]
Oops, you're right! TombATI does include the UB levels, and they do not match the stock ones I have. If so, they are likely to be a modified version with music triggers as you say.

If that's the case, then I'd just hold this **at least until** we ship in much, much ready to use form and we've got not much going on. *Then* I'd decide what to do. Mainly because most users already know about the many versions and they have an easy way to choose. This would just be an extra convenience feature, really low on my priority list.

**Comment by Richard-L** [comment]
Definitely low.

For me the only value to derive might be to offer the different sets of music triggers for TRUB in circulation next to the stock version (=ambient only), and allow the user to choose. A bit overkill perhaps, but curious.

**Comment by rr-** [comment]
This ticket is basically reiterated in a better form by this discussion: https://github.com/rr-/Tomb1Main/discussions/247

Closing and continuing there.
