### ISSUE TITLE
Feature request: Increase Z limit for geometry

### ISSUE THREAD

**Issue by thatguyfrombb** [rr-/Tomb1Main#219]
#211 adds the gameflow options `draw_distance_fade` and `draw_distance_max` to change where the world starts fading to black. Any combination of values over fade at `20480` and max at `28672` will cause the geometry to start popping in and out at visible distance.

**Comment by oziphantom** [comment]
I solved the pop in issue in the 60fps branch, so once can just pull the value changes I made to DepthQ ( which has now be removed) and PhdFarZ ( something like that) to fix this and #220. 
the problem is if you don't have max draw distance, you will see doors and the like glowing off in the distance.

**Comment by rr-** [comment]
Thanks, I tackled this in #211 .
