### ISSUE TITLE
Asset file import

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#246]
Some thoughts on importing the game's assets from genuine copies or dumps. Currently you're pointing to TombATI on the project's landing page which includes copyrighted audio assets someone ripped from an English PS1/Saturn release, as well as the few extra ambient tracks ripped from a PC release, all included as `.flac` files. From a strict point of view this is piracy. I would encourage against such affiliation, and I understand your goal is the removal of any TombATI depency or relation, anyway. As big a franchise it is, you can still legally buy the game even today on either [GOG](https://www.gog.com/game/tomb_raider_123) or [Steam](https://store.steampowered.com/app/224960/Tomb_Raider_I/). Supposedly you can also still buy the game on the PS3 store and emulate the PS1 version.

I understand you still use some code from TombATI currently, beyond just assets. But whenever you can, I would remove the TombATI link and instead advise to copy required assets from whatever sources people have, may that be a dump/image of their physical discs, the discs themselves, files obtained through Steam/GOG, files people may have from the android release if they bought it (the files are identical to PC retail), or even a TR1 PC demo of which several still circulate online. As you'll be aware the demo contains City of Vilcabamba's `LEVEL2.PHD` and the main menu. Else, for the lazy who need an OOBE experience, they could at least try TR1M at hand of Unfinished Business's files which are freeware.

Other than the legitimacy concern, the game has a great wealth of different asset versions, being one of the bigger productions of the 90s, and being released on three main platforms simultaneously, each receiving demos and pre-releases prior. It is one of the larger topics of fan interest to research these asset versions and compare their differences. In fact it opens up a bigger scope beyond just playing the game, one of enabling to use assets from different versions and centrally maintaining and organising them within TR1M. I'm aware this is likely too big an undertaking and not interesting to you, but I find at least worth mentioning. In fact, OpenLara has started doing this already, so I'd hope there might be room for it inside TR1M, too.

But to start, it would be enough to copy files originating from one of the retail PC releases. A very nice and quite extensive overview of them can be found here: https://secretsrunner.web.fc2.com/data_top/tr_top.html

I have two retail releases myself, both with these files in `\DATA`:

| Filename | MD5 |
| --- | --- |
| CRED1.PCX | 6272C2A557CD7597EFC6594E86AE7F2F |
| CRED2.PCX | 4497435DD41ABD9A247BE6AFBF264769 |
| CRED3.PCX | 9DF86E1D2523E3053D07B51CEBF33143 |
| CUT1.PHD | 1041EF2F23F62A740BFA27DF4AB638E5 |
| CUT2.PHD | F5D9CF5A7BB77676D59296D2038BB326 |
| CUT3.PHD | 636AF1916E950924AA3ACB51D2E47010 |
| CUT4.PHD | D2F20F38289A074A103AC9806B0DCD77 |
| EIDOSPC.PCX | B2815D0CC7E8DA83E0A2033A88943D82 |
| END.PCX | 8B678E0162D158C28B7911EF091C6C41 |
| GYM.PHD | 709C060B519862E1666B31562D505684 |
| INSTALL.PCX | 2F4F3EAFF7C99D9F16A530AFB4ECC3B1 |
| LEVEL1.PHD | E4A7F5CB5B70AB5F263FFF6E137FE0E3 |
| LEVEL2.PHD | C2481F4CD320EE5212793DC42DA22281 |
| LEVEL3A.PHD | 62FDE61721CA081BFFEF22360AA9273F |
| LEVEL3B.PHD | 9C071D8285C33C33C657B4EE7D8C9A20 |
| LEVEL4.PHD | 854584F54D98E99769F4D0313DB6B5BB |
| LEVEL5.PHD | AAB0D52E3FE6160DF6B05254449C6540 |
| LEVEL6.PHD | DF3512869F0E8DE3202C125AB2B5FC4E |
| LEVEL7A.PHD | 06D472646A70C8FDDC0F9B5561F111AB |
| LEVEL7B.PHD | 44DB81E97FA70DF98222A868CC460A62 |
| LEVEL8A.PHD | 5128696A7F7A742A2E10E5247FF7A84C |
| LEVEL8B.PHD | 30BA37005FE7C529C3A6CEE5618F5B08 |
| LEVEL8C.PHD | DF49B04B95C9923E5E7DA1095A07E486 |
| LEVEL10A.PHD | 4856B810C97398922283775EFE343AF5 |
| LEVEL10B.PHD | 25DCE79DFC83C5645E6413B80D93E25C |
| LEVEL10C.PHD | FBE5F4E588A90FE23865360C0A3B2C7E |
| TITLE.PHD | 12768DE79512EC9A2E4C49014378666B |
| TITLEH.PCX | 44C7DA52B6DD400F614C7845E6F05DA3 |

The CD also contains audio track assets of the opening theme played with the title screen, audio tracks of the voices and music during cutscenes, and the PC-only ambient tracks. How feasible would it be for TR1M to rip these during an initial setup dialogue?

Further, there are the PC versions of the FMVs as `.RPL`, which I understand aren't all supported yet.

The retail TRUB files I have are:

| Filename | MD5 |
| --- | --- |
| END2.tub | 84DF21D3C2ABD4E36B72EC9F030B1DE3 |
| install.pcx | B0C288E1B33284543C1D0036254DF90E |
| TITLE.PHD | 9BECC9EFBDDD9B24D4687643135EEA49 |
| TITLE.tub | 6272C2A557CD7597EFC6594E86AE7F2F |
| TITLEH.PCX | 4497435DD41ABD9A247BE6AFBF264769 |
| CAT.PHD | 9DF86E1D2523E3053D07B51CEBF33143 |
| CAT.tub | C1F883E4D0B49B34BBE2FF74E81E8ADB |
| cred0.pcx | 9CE02AD3D29F892816BF99047BCDACB4 |
| CRED1.PCX | B2815D0CC7E8DA83E0A2033A88943D82 |
| CRED2.PCX | 8B678E0162D158C28B7911EF091C6C41 |
| CRED3.PCX | 7F7C535BCAB001698A1F965053972F49 |
| EGYPT.PHD | D9812D95E8BDA3E3EA359B2D1D678D6C |
| EGYPT.tub | F03F7A545330D5BA30E2AEC62D47B4A3 |
| EIDOSPC.PCX | 243E3BCE0300E7FCFFB7BC2069DB843C |
| END.PCX | 2F4F3EAFF7C99D9F16A530AFB4ECC3B1 |
| END.PHD | 12768DE79512EC9A2E4C49014378666B |
| END.tub | 12768DE79512EC9A2E4C49014378666B |
| END2.PHD | 3DFBCE6C717400AC8AE9241D3FD25D9C |

Where it seems the `.tub` are unnecessary (?), in the case of the level "END" (Atlantean Stronghold) also apparently perfect duplicates.
 
I amassed 9 TR1 demos which all come with these four files, usually (but not always) matching with the later retail version like so:

| Filename | MD5 |
| --- | --- |
| INSTALL.PCX | 2F4F3EAFF7C99D9F16A530AFB4ECC3B1 |
| LEVEL2.PHD | C2481F4CD320EE5212793DC42DA22281 |
| TITLE.PHD | 12768DE79512EC9A2E4C49014378666B |
| TITLEH.PCX | 44C7DA52B6DD400F614C7845E6F05DA3 |

I would propose to test all the different versions we can find with TR1M in order to maximise compatibility with whatever people have. Also to counter things like #227.

Another step would be to add the fuller range of assets unique to the console releases, mainly the full soundtrack (both PS1 and Saturn), higher quality FMVs (PS1 release), loading screens, localisations of Lara's voice in the gym level (these are all audio tracks on PS1/Saturn), etc. I won't get into these for now, but just for an overview, these were the major releases sans later re-bundles as known to [redump.org](http://redump.org) for both platforms:

| Platform | Releases |
| --- | --- |
| PS1 | `SLES-00024` (UK), `SLES-00485` (FR), `SLES-00486` (DE), `SLUS-00152` (US), `SLPS 00617` (JP) |
| Saturn | `MK81086-50` (EU), `T-7910H` (US), `ST-6010G` (JP) |

And for further reference's sake, if you decided to add support to non-retail versions to allow access to some of their unique assets (different Lara models and textures, unused animations, different sound effects, etc), here's a nice selection of known [demos for all three platforms](https://www.tombraiderforums.com/showthread.php?t=207170) assembled by b122251.

A later feature request would be to offer an asset importer tool with decent UX that parses provided files and unlocks respective aspects of TR in TR1M.

I hope at least some of this is helpful.

**Comment by rr-** [comment]
Regarding the piracy part: you got this the other way around. We do not redirect people to TombATI because it offers some UB assets and we get some code as a bonus. It's the other way around: currently TR1M absolutely *requires* TombATI binaries (.exe, .dll) to even run. If we shipped some stripped down version of TombATI without the UB assets… it would still be illegal, because it still requires proprietary DLLs to play the FMVs.

This issue consists of actually three parts…

- Kill TombATI dependency. This is what we've been doing with all the recent refactors, OpenGL and ffmpeg branches.
- Bundle legal assets from the freeware copy of UB.
- Create some kind of importer as a separate project unrelated to TR1M.

Before anything can happen, we need to finish the work on the first point which is essentially release 2.0 and is in progress. So far we've been getting buried under feature requests but fortunately this has calmed down recently, so we can continue focusing on that.

>Comparison tables

I find it funny that these detailed comparisons do not include the details from the most popular modern options to get the game: GOG and Steam.

>Lazy people

They're not lazy. It is generally quite sensible to expect things to just work. Not everyone has the will or time to fiddle with five registry patches and three tutorials to install a game.

>Piracy (again)

Steam version is bastardized and does not contain music assets, even when people paid money for the "full" version of the game, often for the nth time after buying retail CDs in the past. How do you want to tackle this issue? Everyone who installs TombATI gets the "pirated" tracks with that. When we break off the TombATI dependency, people will install T1M on their Steam versions… then what? "T1M bug: the game doesn't play any music!" "Wait, please run this tool.exe hosted on my private server that will rip the tracks from your CD. Don't have a CD drive? No worries, here's a link to Amazon for cheap offers." I think you will agree that this is less than ideal.
