### ISSUE TITLE
Feature request: Add option near top of gameflow notepad to change format for all FMV videos.

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#259]
Hi, I just wanted to suggest that it might be more user-friendly if there's one overall option in gameflow to choose a FMV format.  For example choosing "avi" would mean all avi type FMVs would play instead of rpl ones.

**Comment by rr-** [comment]
What if we ship .avi by default? We have a mechanism in place that will try various container extensions it supports until it finds one for which the file actually exists. So if we ship with the movies set to .avi, it will try core.avi. It doesn't exist because the user doesn't have HD FMVs? Try core.mkv, core.mp4, core.avi, …, core.rpl. Oh, core.rpl, exists. Play that.

**Comment by atombraiderfan** [comment]
Actually that does sound like a better idea than my suggestion, let's go with that 👍

**Comment by atombraiderfan** [comment]
Hello, thank you again for doing this, and just to let you know that Unfinished Business still defaults to .rpl format videos.  I assume these should also default to .avi as well.
