### ISSUE TITLE
Bug: Atlantis save files incompatible between T1M and Tombati

### ISSUE THREAD

**Issue by nfraihat** [rr-/Tomb1Main#261]
Using a save file for Atlantis created in tombati causes a crash in Tomb1Main and vice versa.
Tried my own saves, and saves downloaded from Stella's website.

The rest of the levels' save files seem to work normally.

**Comment by Richard-L** [comment]
Can you upload the file in question?

**Comment by nfraihat** [comment]
https://1drv.ms/u/s!Alj8A8LGXjOPfX08oMn8V2zplpo?e=hy3njg

**Comment by rr-** [comment]
I think there's something wrong with our ITEM_INFO * reading loop.
![20211215_000910_elu](https://user-images.githubusercontent.com/1045476/146093789-490b1324-76b8-4d80-9ae9-b41e68c8618f.png)

**Comment by rr-** [comment]
This is very difficult to solve due to the savegame files being houses of cards.

Can someone confirm if Bacon Lara is working as expected after loading this save *in the vanilla TombATI*?
We have a strong suspicion that she will not move at all, making the level unplayable. T1M fixes this. If that is the case, I think we can close this issue as an unfortunate consequence of the volatility of the savegame format as `wontfix`, since the level would be unplayable either way.

**Comment by Richard-L** [comment]
@rr- Using the above save in **vanilla TombATI** and playing the level up to bacon Lara, she works fine if played in concession:

https://user-images.githubusercontent.com/4934209/146593497-4aff9c7f-2b63-432f-b7e6-932383868768.mp4

She freezes if you save and load whilst she's still alive:

https://user-images.githubusercontent.com/4934209/146593764-b26fa6ed-9f35-4c3d-b04a-9d0450ddcedd.mp4
