### ISSUE TITLE
Audio Glitching / Popping 

### ISSUE THREAD

**Issue by walkawayy** [rr-/Tomb1Main#281]
Multiple reports of audio glitches on the new 2.0 release. There's a few forum posts and a few Discord ones. 

https://www.tombraiderforums.com/showpost.php?p=8334800&postcount=112

Someone posted this video. First clip is TombATI, second is the 2.0 release. You can hear the popping.

https://user-images.githubusercontent.com/81546780/146648221-b610778d-cd53-48fb-bd53-ef21ac678cdc.mp4

**Comment by Richard-L** [comment]
I don't have this at all.

Any chance it has to do with a particular sound hardware setup?

**Comment by rr-** [comment]
I don't know how to fix it or what's the cause and I'm open to suggestions.

**Comment by walkawayy** [comment]
Is there stereo sound now? I noticed for gunshots, they sound like they are more in the left or right ear. But it seems to depend on where the bullets land relative to Lara, not the camera.

To stay on topic, I do notice the popping in Atlantis. It doesn't seem to stop and is pretty annoying. I could help debug but I honestly know nothing about the audio code.

**Comment by rr-** [comment]
No worries, I can walk you through it:

The audio code uses SDL mixer. To play audio with SDL, we need to supply its mixer with actual samples, e.g. numeric values representing the actual sound amplitude, at a certain speed of _x_ values per second. The _x_ is called sampling rate. To visualize this concept:

![](https://www.izotope.com/en/learn/digital-audio-basics-sample-rate-and-bit-depth/_jcr_content/root/sectioncontainer_main/flexcontainer/flexcontainer_center/flexcontainer_center_top/image_1558274996.coreimg.82.1280.jpeg/1620658129121/reconstructing-the-original-signal.jpeg)

Multiple channels means just a few different sound streams. We also need to mix the sounds together from multiple sources, but it's only a matter of adding the amplitudes together (sample values can be negative. They should be contained within -1.0 … +1.0 range). This mixing is done in `S_Audio_MixerCallback`.

There are two kind of sources in T1M that produce sample values: stream sounds and sample sounds.
- Streams are used to play the background music: we decode and convert the music files on the fly with libavcodec. This is because loading them all at once would take considerable amount of memory.
- Samples are used to play all the SFX: gunshots, Lara's grunts, wolf howling etc. We decode and convert them once per level load, because they're small enough that we can hold all of them in their entirety in the memory.

Decoding means we take a FLAC music file or a WAV sample (embedded in the .PHD level file) and retrieve raw sample values.
Converting means converting these raw sample values to a form usable by the mixer. The source files can use different layouts, sample rates and channel counts, whereas the mixer is fixed to play the samples in stereo, using float values, at 44.1 kHz sample rate. For example if we try to play 22 kHz sample via 44.1 kHz mixer, we'll play it twice as fast and it will have very high pitch. If we try to play `uint8_t` samples via `float`, we'll get some garbage that probably will somewhat sound like the original but will be very loud and extremely noisy.

The decoding part is done by libavcodec, whereas the sample format and rate conversion is handled by SDL (SDL_NewAudioStream).

Apart from this, sample sounds can have some variation on how they are played:

- volume (whether they're more or less audible). TombATI used [IDirectSoundBuffer_SetVolume](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708939(v=vs.85)) which expects the volume to be specified as attentuation in hundredths of decibels (dB). We use simple multiplication of sample values. To work out the formula in `S_Audio_DecibelToMultiplier` that gets from the decibels to the multiplier, I checked wine sources.
- pan (whether they're more audible in the left channel or the other channel). TombATI used [IDirectSoundBuffer_SetPan](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708938(v=vs.85)) which expects the pan to be specified as -decibles for the left channel or +decibles for the right channel. I don't remember how I arrived at the current solution which is just adding the pan to the volume multipliers of the left and right channel, it was a combination of TombATI / wine consulting.
- pitch (whether the sounds should be played in lower or higher frequencies). We achieve this by incrementing the sample pointer by a floating point value representing the speed (usually 95%-105%) instead of 1. Note that this does not offer interpolation so there will be two samples played in a row and sometimes 0. It would be nice to have interpolation here.

As far as I can think, the potential sources of clicks are as follows:

- poor decoding.
- poor conversion. If you try to play Atlantis Scion hum sample data that was made after converting with SDL audio streams with ffmpeg, you'll notice that they click and it's not really our fault. I don't know what to do about it.
- pitch not using interpolation. (unlikely)
- sample values being added together going beyong -1.0 … +1.0 range (unlikely, because the clicks happen only near the end of the samples).

A potential solution to point 2 would be to use libavcodec-based sample format conversion instead of SDL.

Also in case you'll want to consult with the TombATI implementation – don't bother reverse engineering the game, it's all implemented by GLRage anyway and all the sample sound code can be found in their repository. (Music sound in OG is handled separately by a library called libzplay, for which there's a small wrapper impersonating the winmm library that the OG .exe is linked to load at runtime).

**Comment by walkawayy** [comment]
I might be over my head on this. The only thing I noticed so far was `AUDIO_SAMPLES 500` in `s_audio.h`. According to the [SDL docs](https://wiki.libsdl.org/SDL_AudioSpec#remarks), this value should be a power of 2. I also read a few forum posts that a higher value like 2048 might fix popping, but that did not fix anything for me. It also only seems to pop on certain animations.

**Comment by walkawayy** [comment]
Here's another thing I noticed while testing the Evil Lara save bug. At the beginning you can hear more popping audio, but also at 22 seconds in, notice how the Uzi sounds just go away while the mutant explodes. Too many audio streams maybe?

https://streamable.com/uvi5ub

**Comment by rr-** [comment]
Possible, there are 10 slots. I'll raise it to 20.

**Comment by oziphantom** [comment]
> I might be over my head on this. The only thing I noticed so far was AUDIO_SAMPLES 500 in s_audio.h. According to the SDL docs, this value should be a power of 2. I also read a few forum posts that a higher value like 2048 might fix popping, but that did not fix anything for me. It also only seems to pop on certain sound effects.
You want power of two. 

Popping has two main causes
a.) buffer underflow, to which adding more samples to the buffer solves

b.) Sound not ending on a 0 or being cut short and hence a value goes from high to 0 or low to fast. Which can be a missing = on a < somewhere, could also be poor sample data, maybe the end of the sample gets cut off in the PHD data. Printing out the last value of each sample would test that theory. Possibly in the mixing a channel gets dropped mid play, although with the heart beat that doesn't sound right there is not enough going on. However the heartbeat could be restarting to soon or two late as you are resampling the audio the "number of samples to loop at" might be off by a sample or 4. 

With dropping sounds, general audio rule is don't mix more than 3 sounds at once, over 3 becomes too hard for the brain to separate them clearly. So a priority system is usually employed, but you can't just stop the other samples, but need to do a rapid ease out volume fade to avoid any popping.
