### ISSUE TITLE
Bug: Savegame Crystals issue with Lara's Home

### ISSUE THREAD

**Issue by xKinomoto** [rr-/Tomb1Main#289]
This bug occurs when I enable the Savegame Crystals.

When going into Lara's Home level, after the initial cutscene, it prompts me to start a New Game. I click it, then going through the Home level goes all right, but when it ends, I can see it left a savegame of it.

Happens in Version 2.1

https://user-images.githubusercontent.com/24980563/147697502-2fba73af-a73d-4357-959f-148d5d1a32fb.mp4

![image](https://user-images.githubusercontent.com/24980563/147696955-418a65b8-9931-415e-bbba-8ac712f4baf8.png)

**Comment by walkawayy** [comment]
Got a fix ready, but I did notice in save crystal mode there's no option to refuse to save. You have to save to continue. Only reason I cared is because I have a lot of saves in different testing locations lol. I guess most people obviously want to save at level completion. Maybe if we can ever increase the number of save slots this won't matter at all.
