### ISSUE TITLE
Feature request: save level stats to be used later

### ISSUE THREAD

**Issue by Rapora9** [rr-/Tomb1Main#336]
Right now we can edit the gameflow file to determine when the game should show stats screen. However, if you command it to show for example level_1 stats after completing level 3, they're incorrect – probably because they're not saved anywhere and are overwritten by the new level.

This feature would be useful mainly for custom levels, but it can be used in main game too. For example, you could make it so that after completing the final level, the game would show statistics for every level, one after another, to short of recap the experience.

This might easily be too hard to achieve for something so "meaningless" but I'd definitely have use for it...

**Comment by walkawayy** [comment]
This should be possible after #277 is done. We will need all this info for restart level too.

**Comment by rr-** [comment]
@walkawayy IDK if this is a good place to ask but is there anything else we should consider before going with the release in regard to the savegames? I want to cram into 2.6 as many tickets that are related to this as possible, so that we don't have to deal with backwards compatibility for as long as we can.

**Comment by walkawayy** [comment]
I'll open a discussion about it.
