### ISSUE TITLE
Bug: Lava trap does not kill Lara

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#353]
In the corridor with the unreachable medi packs, after pulling switch, the lava does not kill Lara and instead pushes her away.

![20220118_150412_Atlantis](https://user-images.githubusercontent.com/94776985/149964900-4e9ef2c0-6688-4cdd-9a59-3bfa0a5b988c.jpg)

I have to say I like this bug ;)

**Comment by walkawayy** [comment]
F probably related to #293. I'll take a look.

**Comment by walkawayy** [comment]
Hm I just downloaded version 2.1, before #293, and the trap doesn't set Lara on fire before the switch is pulled in that version either. Here's the current behavior:

https://streamable.com/zppv5d

**Comment by rr-** [comment]
Check also normal fires and Midas fire room.

**Comment by rr-** [comment]
I'm pretty sure it's a T1M bug but you might want to check original TombATI (which doesn't run on Wine so I can't really test).

**Comment by walkawayy** [comment]
Yes later today I am going to test TombATI and PS1.

**Comment by rr-** [comment]
To hopefully save you some searching, this trap is called "Lava Wedge".

**Comment by Richard-L** [comment]
I tested it on PS1:

https://user-images.githubusercontent.com/4934209/150020812-6f5728d0-24b6-469d-a67b-42b150fb277c.mp4

https://user-images.githubusercontent.com/4934209/150020823-e0059549-f914-4a0a-a4b6-14aa58a02188.mp4

As I thought this is expected behaviour. The trap isn't a trap before you pull the lever. It's only hurting Lara once it's moving. It's the same for the same 4 traps in the room in "Great Pyramid" near the end of the level, which trigger their movement based on a tile you step on instead of the lever.

I would not change this. It's too big of a game dynamic alteration in my opinion.
