### ISSUE TITLE
OG bug: Pierre's dropped items disappear after reload

### ISSUE THREAD

**Issue by rr-** [rr-/Tomb1Main#396]
Food for thought for #277 
I'm surprised nobody reported this earlier.

Applies to all dynamically spawned items.

**Comment by walkawayy** [comment]
Hm. It seems like the game tried to do something for that and maybe it's just broken in `savegame.c`
```
        if (item->object_number == O_PIERRE && item->hit_points <= 0
            && (item->flags & IF_ONESHOT)) {
            if (Inv_RequestItem(O_SCION_ITEM) == 1) {
                SpawnItem(item, O_MAGNUM_ITEM);
                SpawnItem(item, O_SCION_ITEM2);
                SpawnItem(item, O_KEY_ITEM1);
            }
            g_MusicTrackFlags[MX_PIERRE_SPEECH] |= IF_ONESHOT;
        }
```

**Comment by rr-** [comment]
Don't tackle this yet @walkawayy I'll be doing heavy refactors to the savegame system and we'll end up having tons of conflicts otherwise.

**Comment by rr-** [comment]
It's now free to take, as we merged the big stuff in. It'd be nice to include in 2.6 but I have no clue what might be the reason why it's not working hence I haven't added it.

**Comment by walkawayy** [comment]
One option for why it was bugged:
I couldn't figure out how to correctly get the legacy save system to save and load to see why it's broken in the OG game (the requestor was legacy but saving didn't work). The OG game saves flags like this:
```
            uint16_t flags = item->flags + item->active + (item->status << 1)
                + (item->gravity_status << 3) + (item->collidable << 4);
```
while the new system saves variables like `gravity_status` separately. So that's  The flags were saved wrong somehow.

The second reason it could be bugged:
I am just testing this on the new BSON save games for now. Something odd is going on with Scions.

1. I grabbed the one in Qualopec giving me 1 Scion in inventory.
2. I killed Pierre and he drops one Scion.
3. I saved without picking it up.
4. I reload the save and I have 3 Scions.

This seems to happen when Pierre is loaded which is odd. The game records a Scion piece as `O_SCION_ITEM`, `O_SCION_ITEM2`, and `O_SCION_OPTION` and then the `if (Inv_RequestItem(O_SCION_ITEM) == 1)` fails because it returns 3 and not 1. I think T1M then has an additional bug that is tripling it in the inventory screen too. So maybe the OG bug would be fixed if this tripling is fixed? Here's a log snippet:

```
../src/game/savegame.c 124 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM): 1
../src/game/savegame.c 126 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM2): 1
../src/game/savegame.c 129 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM3): 0
../src/game/savegame.c 132 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM4): 0
../src/game/savegame.c 135 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_OPTION): 1
../src/game/savegame.c 140 SaveGame_LoadPostProcess Pierre item->object_number: 28, item->hit_points: -16384, oneshot: 256
../src/game/savegame.c 151 SaveGame_LoadPostProcess Spawn Pierre 1.
../src/game/savegame.c 124 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM): 3
../src/game/savegame.c 126 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM2): 3
../src/game/savegame.c 129 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM3): 0
../src/game/savegame.c 132 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_ITEM4): 0
../src/game/savegame.c 135 SaveGame_LoadPostProcess Inv_RequestItem(O_SCION_OPTION): 3
```

**Comment by rr-** [comment]
@walkawayy could you test this only with the new saves? It seems to be working fine for me.

Also to get the legacy system to save and disable BSON, you can fiddle with `allow_save` and `allow_load` in the `static const SAVEGAME_STRATEGY m_Strategies[]` array.

**Comment by walkawayy** [comment]
I'll clean out my old and new saves, and move them to a backup folder to make sure.

Also I need to do a legit play of Natla's Mines to test them I guess. Looks like the baddies have checks when loading a game to not spawn their weapon if Lara has the gun already. However, they do not have that check when dropping.

```
```

**Comment by rr-** [comment]
The way I see it it's working OK with the new saves and we don't actually need to do anything.

IMO the baddies are now acceptable. I can make the baddies not drop the items if Lara has the guns but that will complicate max pickups – if I added this, you'd need to go kill Baldy, have him drop the shotgun, and traverse back to the secret above the lava lake near Cowboy for max%. Annoying IMO and not worth it.

**Comment by walkawayy** [comment]
I agree we can close it.

**Comment by rr-** [comment]
https://www.youtube.com/watch?v=rW6M8D41ZWU
