### ISSUE TITLE
SFX Volume preference

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#421]
I've noticed as of some of the more recent builds that SFX volume seems to have a "priority" for lack of a better world.

Listen to the gunshots and wolf grunts switching from full to reduced volume in this example:

https://user-images.githubusercontent.com/4934209/153091924-1c0ac7e0-e79a-4aca-95cb-06b2faa4abea.mp4

Hadn't these always been full volume regardless of situation? :thinking: In any case, it's odd how Lara's guns are suddenly much quieter.

**Comment by rr-** [comment]
Uhhh… How does this even happen?

**Comment by rr-** [comment]
Is there a consistent setup to reproduce this issue?

**Comment by Richard-L** [comment]
Sadly it's quite random. I can't seem to find anything. Here are a few examples:

https://user-images.githubusercontent.com/4934209/153095353-3f28b03b-803a-460b-a0de-5e509c6d8607.mp4


https://user-images.githubusercontent.com/4934209/153095355-eacb3f64-1253-4b67-b9ae-88a08ef2764b.mp4


https://user-images.githubusercontent.com/4934209/153095360-6a7113d1-e4a7-4caa-88d9-769fa8fc4f3d.mp4


https://user-images.githubusercontent.com/4934209/153095366-1a5fe770-69c3-464c-9d8a-171a17b1dbe7.mp4

**Comment by walkawayy** [comment]
I've noticed this for a while but thought it was an original game bug trying to do like stereo sound lol.

**Comment by rr-** [comment]
Theory: SDL thread finishes playing a sample and marks it as inactive in s/audio/sample. The sample is now free to take.
The game loop plays. Lara shoots guns. We play a new sound via Sound_Effect. It obtains the first available sample. But it happens to be the same sound that we just closed in the SDL thread. It assigns it a new slot. Now two slots point to the same sample, one that just finished playing, and another that just started.
Sound_UpdateEffects calculates the volume. It uses S_Audio_SampleSoundIsPlaying to determine if a sample is playing, and it is! For both slots. So it assigns both of these slots different volumes that override each other and lead to chaos.

If that indeed is the case, moving Sound_UpdateEffects to the start of the game loop won't solve the issue as we will still have data races. We probably need a mutex so that the samples always stop in the main thread and the game can learn about it.

Just my thinking…

**Comment by rr-** [comment]
`Sound_ClearSlotHandles` protects against the very scenario that I described above. Meh

**Comment by rr-** [comment]
Found it!
I'll reward myself with some sleep…
