### ISSUE TITLE
ALT+ENTER triggers game actions

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#479]
When you use the ALT+ENTER shortcut to toggle fullscreen/windowed mode, the game will recognise either ALT or ENTER as inputs, and do things like open the passport, skip FMVs, make Lara jump, etc. Is it possible that this isn't the case?

Generally didn't we have a discussion somewhere on the default buttons still having an effect unintentionally, even if the user has chosen different keybinds?

**Comment by rr-** [comment]
I think we did. I would pause this until we deal with #241 .

**Comment by rr-** [comment]
@Richard-L the original bug was about alt+tab causing Lara to keep jumping even when the window is out of focus.

How do you expect us to recognize at the time the user starts to press alt, if they intend to press enter after, or if they intended to jump?

We can't change the game to react to key releases instead of key presses, as it'd utterly ruin the experience.

>Generally didn't we have a discussion somewhere on the default buttons still having an effect unintentionally, even if the user has chosen different keybinds?

This is a separate issue and needs its own discussion. Can you open a ticket for this?

**Comment by Richard-L** [comment]
> How do you expect us to recognize at the time the user starts to press alt, if they intend to press enter after, or if they intended to jump?

Yeah it's unfortunate. An easy solution would be to remap the fullscreen toggle to one of the function keys perhaps. But it's not desirable imo to break the `ALT`+`ENTER` convention.

Is the question of keys like `ALT` having an effect regardless of TR1M being in focus or not still relevant? If not, then this can be closed.

**Comment by rr-** [comment]
>Is the question of keys like ALT having an effect regardless of TR1M being in focus or not still relevant? If not, then this can be closed.

I don't think so, this has been long fixed. We'll continue in #564.
